# Properties applied for any profile
# Extract here the common parts from all profiles and override only the neccesary parts
# Try to update all the profiles if you made a required change to your profile

server:
    port: 8080

spring:
    profiles:
      active: local-mysql
    queries:
      users-query: select username, password from users where username=?
      roles-query: select u.username, r.role from users u inner join user_role ur on(u.id=ur.user_id) inner join role r on(ur.role_id=r.id) where u.username=?
    mail:
      apikey:
      formularedir: /home/user/formulare
    documents:
      rootServerLocation: /home/coruptiaUcide/documents
      templatesServerRelativeLocation: /templates
      uploadedServerRelativeLocation: /uploads

---

# Local development profile

server:
    port: 8090

spring:
    profile: local-mysql
    main:
        web-environment: false
    datasource:
        url: jdbc:mysql://localhost:3306/weesee
        username: root
        password: <local-password>
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 5
        max-pool: 10
        max-idle: 0
    jpa:
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    documents:
        rootServerLocation: /<project-path>/vavedem/documents

---

# Profile used in the test environment

server:
    port: 8090

spring:
    profile: test-mysql
    main:
        web-environment: false
    datasource:
        url: jdbc:mysql://localhost:3306/weesee
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 5
        max-pool: 10
        max-idle: 0
    jpa:
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    documents:
        rootServerLocation: /opt/apps/weesee/data/documents